### ISSUE TITLE
Flag data not up to date

### ISSUE THREAD

**Issue by thereals0beit** [4chan/4chan-API#19]
The flags image URLs in the API docs are incorrect, these days there's only one flag image and 4chan uses CSS sprite rendering techniques to render the flag properly.

If there was some sort of API to grab flag data (flag image which you only load once, per board) and if each post had a 'flag_x' and 'flag_y' so we could select the proper flag from the sprite, I think this would work.

**Comment by puromonogatari** [comment]
Alright, so, this has become an issue again on /pol/
https://s.4cdn.org/image/country/troll/au.gif
https://s.4cdn.org/image/country/troll/gb.gif
https://s.4cdn.org/image/country/troll/de.gif

Once again I have to recommend just outputting the x/y data for the sprite, but if not, these images need to be generated.

/int/ and associated "normal" flag boards appear to be working fine.
