### ISSUE TITLE
thumbnail resource path

### ISSUE THREAD

**Issue by neuro-sys** [4chan/4chan-API#24]
Thumbnail resource URLs have a seemingly random subdomain prefix which is an integer.

The document says:

>Thumbnails: http(s)://t.4cdn.org/{board}/{tim}s.jpg

Whereas in reality this URL can be like this:

http://0.t.4cdn.org/v/99999999s.jpg

I couldn't find anything related in the documentation.

**Comment by mootykins** [comment]
We load thumbnails from "0/1.t.4cdn.org" to speed up thumbnail loading in older web browsers. We may change this in the future though, which is why we request people using the API to always use "t.4cdn.org" to load thumbnails.
