### ISSUE TITLE
Thumbnail urls broken after change

### ISSUE THREAD

**Issue by puromonogatari** [4chan/4chan-API#25]
If you're using the catalog to display information, you usually have something like:

		getThumbnailUrl: function(data) {
			if(typeof(data.tim) == 'undefined' || data.filedeleted == 1 || (data.tn_w < 10 && data.tn_h < 10)) {
				return 'https://s.4cdn.org/image/filedeleted.gif';
			}
			
			if(data.spoiler == 1) {
				if(typeof(data.custom_spoiler) != 'undefined' && data.custom_spoiler > 0) {
					return "https://s.4cdn.org/image/spoiler-" + Board.current + data.custom_spoiler + ".png";
				} else {
					return "https://s.4cdn.org/image/spoiler.png";
				}
			}

			return "https://t.4cdn.org/" + Board.current + "/" + data.tim + "s.jpg";
		},

The problem is, the "t" subdomain isn't the only valid subdomain for thumbnails anymore.

Now I'm seeing:
http://0.t.4cdn.org/(board)/(time)s.jpg
"0.t.4cdn.org" - I'm not sure where this "0" comes from.

There doesn't seem to be any recent commits to the API documentation which explain this behavior.

**Comment by desuwa** [comment]
You mean urls like `//t.4cdn.org/{board}/{tim}s.jpg` don't work for you anymore?

**Comment by puromonogatari** [comment]
Ah, you know what - I woke up this morning, saw a large amount of thumbnails not loading and attributed it to this added subdomain when that may not be the case.

It seems to be working fine now, the main issue was that images on that subdomain were not loading earlier (probably downed server or reboot or whatever).

Either way, I believe it's working now so I'll close this.

**Comment by neuro-sys** [comment]
The issue persists. Arbitrary files are not available thorugh t subdomain, but only with 0. or 1. preprended to it.

**Comment by Floens** [comment]
https://0.t.4cdn.org/g/1390842451744s.jpg
and
https://t.4cdn.org/g/1390842451744s.jpg

Both work fine.

**Comment by puromonogatari** [comment]
@neuro-sys have you tried refreshing later? I'd assumed the issue was because one of the CDN servers was down or slow, but if that's not the case I guess more information is required.

It's happening to me right now actually, 
https://t.4cdn.org/a/1421020168476s.jpg
vs
https://0.t.4cdn.org/a/1421020168476s.jpg

The 0 url works, normal does not.

**Comment by Floens** [comment]
referer something something
