### ISSUE TITLE
/qa/ missing from boards.json

### ISSUE THREAD

**Issue by Floens** [4chan/4chan-API#27]
/qa/ is missing from the boards.json list. I don't know if you are going to keep the board around, but users from Clover can't add the board if it is not in boards.json.

**Comment by ccd0** [comment]
To 4chan admins: If you want to have unlisted boards, perhaps you could add a
https://a.4cdn.org/[board]/board.json
?

**Comment by beschoenen** [comment]
I've added this board to my fork by adding it as a standard board. it kept working after this (removing, readding & etc.)
