### ISSUE TITLE
If-Modified-Since without function

### ISSUE THREAD

**Issue by RoyalBingBong** [4chan/4chan-API#30]
Have a small personal project in nodejs and I found out that the 'If-Modified-Since' header does not seem to work ([anymore](http://stackoverflow.com/questions/19204054/)), thus never returning the supposed 304 when the json has not been changed. API rule 3 is rendered useless because of this.

Here a snipped for nodejs with request:
```javascript
var request = require('request')
var options = {
  uri: 'url of a random json that has not been updated',
  json: true,
  headers: {'If-Modified-Since': new Date().toUTCString()}
}
request(options, function(err, res, body) {
  console.log(options.headers['If-Modified-Since'] + ' - If-Modified-Since')
  console.log(res.headers["last-modified"] + ' - last-modified')
  console.log('StatusCode: ' + res.statusCode)  
})
```
Sample output, that should yield a 304, bceause it was last modified an hour ago:
```
Mon, 31 Aug 2015 02:24:24 GMT - If-Modified-Since
Mon, 31 Aug 2015 01:26:01 GMT - last-modified
StatusCode: 200
```

Or did I miss something here?

**Comment by ccd0** [comment]
It works if you send exactly the date from the Last-Modified header.

**Comment by RoyalBingBong** [comment]
Thank you! This helps a lot. Will fix my code accordingly.
