### ISSUE TITLE
rolling threads

### ISSUE THREAD

**Issue by bui** [4chan/4chan-API#34]
can we have an attribute to indicate these?

**Comment by Floens** [comment]
Are there rolling threads then?

**Comment by bui** [comment]
yeah, they're fairly recent, if a rolling thread hits >1000 replies the old posts are pruned.

example here:
https://boards.4chan.org/pol/thread/55581283

there's around ~5000 posts as of writing if you check the archive

**Comment by Floens** [comment]
Neat

**Comment by desuwa** [comment]
There's a `sticky_cap` property now showing the maximum number of replies for self-pruning.

**Comment by Floens** [comment]
Neat, thanks. Is an icon in the making?

**Comment by desuwa** [comment]
>Is an icon in the making?
No.
"Rolling" stickies is a fairly old feature. It's just that it started being used actively only recently.
