### ISSUE TITLE
No CORS headers

### ISSUE THREAD

**Issue by franzwr** [4chan/4chan-API#35]
>CORS is supported with an origin of http(s)://boards.4chan.org

Persuing the response headers, I see no `Access-Control-Allow-Origin` header in either boards.4chan.org or a.4cdn.org.

![screen shot 2016-01-05 at 17 05 02](https://cloud.githubusercontent.com/assets/4754508/12120064/5f1ff8f0-b3cf-11e5-9a6c-1a77fac5d2e7.png)

![screen shot 2016-01-05 at 17 09 11](https://cloud.githubusercontent.com/assets/4754508/12120063/5f1c2a04-b3cf-11e5-9202-3909eb5d4255.png)

**Comment by desuwa** [comment]
You won't get back access control headers if you don't send the right Origin.

```
~ > curl -I -H "Origin: http://boards.4chan.org" http://a.4cdn.org/boards.json
HTTP/1.1 200 OK
Access-Control-Allow-Origin: http://boards.4chan.org
Access-Control-Allow-Methods: GET, OPTIONS
Access-Control-Allow-Headers: If-Modified-Since
```

**Comment by franzwr** [comment]
I see, I thought said headers (allowing only boards.4chan.org) would appear from any origin. Thanks!

**Comment by ccd0** [comment]
@desuwa
Why are you still trying to get visitors to install malware?

**Comment by Floens** [comment]
mad cash
