### ISSUE TITLE
New Manager Capcode

### ISSUE THREAD

**Issue by r3c0d3x** [4chan/4chan-API#38]
A new capcode for managers has been spotted in the wild, but has yet to be documented! Would you mind including something for this?

Example Post [dead]: http://boards.4chan.org/qst/thread/5#p639
HTML: http://pastebin.com/cLvjrcvf
Screenshot: https://i.imgur.com/iJPGwRG.png

**Comment by r3c0d3x** [comment]
I'm assuming that it would just be `manager` as a new `capcode` option, `Manager` as a new `id` option, and [this](https://s.4cdn.org/image/managericon.gif) (got this from the post's HTML, appears to work) as the manager icon URL.

**Comment by Floens** [comment]
It's been in the css since forever.

**Comment by catamphetamine** [comment]
So who's a manager exactly?
The scheme seems too complex: admins, founders, devs, managers...
I'm settling on this:

```js
function parseRole(capcode) {
	switch (capcode) {
		case 'admin':
		case 'founder':
		case 'developer':
			return 'administrator'
		case 'mod':
		case 'manager':
			return 'moderator'
	}
}
```

So is a "manager" more of a "moderator" or an "administrator"?

**Comment by desuwa** [comment]
A `manager` is a Manager just like a `developer` is a Developer and a `founder` is the Founder
