### ISSUE TITLE
Document which characters are escaped

### ISSUE THREAD

**Issue by ccd0** [4chan/4chan-API#43]
It would be useful to document which characters are escaped so that they can be easily converted back to the original text. I thought it was just the stuff necessary for insertion into HTML
`'&amp;': '&', '&#039;': "'", '&quot;': '"', '&lt;': '<', '&gt;': '>'`
but I'm now also seeing `&ccedil;` at https://a.4cdn.org/pol/thread/79102063.json in the country name of Curaçao.

Whether or not this is a bug, the fact that most of the fields have their characters escaped (not just the comment) should be documented.

**Comment by desuwa** [comment]
> I thought it was just the stuff necessary for insertion into HTML

That's how it's supposed to be for every field where it makes sense.
Although, the single quote isn't always escaped.

I've updated the country names for consistency.
