### ISSUE TITLE
Last modification/bump date field for threads in catalog.json

### ISSUE THREAD

**Issue by zsau** [4chan/4chan-API#45]
It would be useful to have a field in the thread objects in `catalog.json` that is guaranteed to change when the thread is bumped or otherwise modified. We can't reliably use `replies` nor `last_replies`  for this because a reply could get added and then deleted between fetches of `catalog.json`.

I did notice the field `last_modified` in the README, but haven't seen it used yet. Is this only for posts that are edited (e.g. USER WAS BANNED)?

**Comment by desuwa** [comment]
Threads are already sorted by bump date in catalog.json
threads.json has a last_modified field which is updated on new replies, deleted posts and images, public bans and when thread settings are modified (sticky, perma sage, etc...)

**Comment by zsau** [comment]
That's useful info, thanks. Re: `catalog.json`, I know the threads are sorted by bump order. However, in my app I need to calculate the diff between one catalog and the next so I can animate my UI appropriately. A field like `last_modified` in catalog.json would make this significantly easier, without forcing another network fetch (my app currently doesn't use `threads.json`).

**Comment by desuwa** [comment]
You absolutely need the difference in seconds? Knowing the position of threads (order) isn't enough?

**Comment by zsau** [comment]
No, the time isn't important; I just need some way to know which threads actually changed. When I pull a new version of `catalog.json`, I want to do an animation for any threads that changed. That's not straightforward to do from just the order, because (for example) a thread could end up a the top via another thread being deleted, rather than by being bumped itself.

**Comment by desuwa** [comment]
Should be good now.

**Comment by zsau** [comment]
Great, thanks!
