### ISSUE TITLE
add new json_tail_size added to boards.json to docs

### ISSUE THREAD

**Issue by pokeball99** [4chan/4chan-API#46]

**Comment by Floens** [comment]
boards.json isn't documented at all, not just json_tail_size. And really, isn't it clear what it does?

**Comment by desuwa** [comment]
I removed that property. `tail_size` from individual thread jsons should be used instead (not documented yet).

**Comment by catamphetamine** [comment]
For anyone googling for `tail_size` I documented it here:
https://github.com/catamphetamine/chanchan/blob/master/docs/4chan.org/API.md#auto-refresh
