### ISSUE TITLE
"Immortal threads" create incorrect post/image limits in the API

### ISSUE THREAD

**Issue by ipatrol** [4chan/4chan-API#48]
For whatever reason, this seldom-used feature causes the post and image limits to be reported as 1, instead of as 0 like they are for stickies. This interferes with both native and user extensions, making it difficult to post images.

Since this is a feature rarely seen in action, I have attached the API output from the thread that brought this to MVB's, and therefore my, attention:
[https _a.4cdn.org_a_thread_152333795.json.txt](https://github.com/4chan/4chan-API/files/710139/https._a.4cdn.org_a_thread_152333795.json.txt)

Side note: I'm more used to APIs returning -1 to mean infinite/unlimited, as opposed to 0. Since we do have locked stickies, which might confuse a client not equipped to deal with them, I would suggest we consider at some point making the reported post/image limits for stickies and immortals as -1.

**Comment by desuwa** [comment]
Should be fixed now
