### ISSUE TITLE
API & CDN Endpoints returning http 503 errors

### ISSUE THREAD

**Issue by i80386** [4chan/4chan-API#58]
Hello,

I'm a developer of a small archive tool that can monitor & download threads/images.

Sometime this week my tool started to log a bunch of http 503 errors, for catalog and thread updates, but also for the images. In firefox (without ad blockers or any add-ons running) the thread updating seems to stop working too.
I noticed when I get a new ip address from my isp (I have a dynamic ip address) the tool works for some time without problems before it starts logging 503 error again.

My tools wait at least 30 seconds before requesting thread or catalog infos again, uses the same protocoll and makes requests with the "if-modified-since" header.

**Comment by desuwa** [comment]
https://github.com/4chan/4chan-API/issues/57
