### ISSUE TITLE
Thumnail endpoint unavailable

### ISSUE THREAD

**Issue by Floens** [4chan/4chan-API#60]
The thumbnail endpoint (`t.4cdn.org`) is currently unavailable.
The site currently uses the i domain for thumbnails, and that does work. Could the t domain be redirected to the i domain?

**Comment by balthazar** [comment]
In addition, using the `i.4cdn.org` route on an external website triggers a 403 response code.

**Comment by desuwa** [comment]
Yeah the doc is outdated.
t.4cdn.org hasn't been used for some time already and won't be coming back, not even as a redirect.
Please use i.4cdn.org instead.

@balthazar 
That must be the hotlink protection.

**Comment by balthazar** [comment]
@desuwa Indeed, thanks
