### ISSUE TITLE
Rule 3

### ISSUE THREAD

**Issue by CamFerguson** [4chan/4chan-API#61]
- Use If-Modified-Since when doing your requests.

Code looks something like
>         headers={'If-Modified-Since': pastResponseTime}
>         query = 'https://a.4cdn.org/pol/thread/' + str(id) + '.json'
>         response = requests.get(query, headers)

Using either current GMT or header 'last-modified' always returns <200> rather than the <304> desired.

**Comment by bakugo** [comment]
You're using the requests library wrong. Second parameter is `params` by default, not headers.
Use this instead: ``requests.get(query, headers=headers)``

**Comment by CamFerguson** [comment]
thanks
