### ISSUE TITLE
Sorting threads by id/last comment/post time

### ISSUE THREAD

**Issue by westdabestdb** [4chan/4chan-API#62]
It would be great to be able to sort threads by thread id, reply count, last modification and so. Am I missing something or these features doesn't exist?

**Comment by bakugo** [comment]
The catalog endpoint contains every single thread on a board, with all of that information. What's stopping you from sorting them clientside?

**Comment by westdabestdb** [comment]
Thank you, I was wondering if it's possible in the API, but sorting them in client-side works too.
