### ISSUE TITLE
What's the endpoint for getting "Popular Threads"?

### ISSUE THREAD

**Issue by catamphetamine** [4chan/4chan-API#64]
On the main 4chan page there's the "Popular Threads" section.
What's the data source API endpoint for that?
E.g. getting a list of threads with their "scores" or "ratings" or "speed" (posts per second/minute).
There seems to be none in the docs.

**Comment by catamphetamine** [comment]
Looked at "Chanu" source codes: it seems to parse `4chan.org` main page HTML to get the list of "Popular threads" instead of using an API endpoint.
https://github.com/grzegorznittner/chanu/blob/8a65b87847ff1aea0366cf3c1e03d70edb94e36c/app/src/main/java/com/chanapps/four/service/FetchPopularThreadsService.java

What about [4stats.io](https://4stats.io/) then?
Do you use an API endpoint or do they also just parse HTML?

![image](https://user-images.githubusercontent.com/477167/52383563-01c4b480-2a8b-11e9-8ffd-ab0067b037f3.png)

**Comment by catamphetamine** [comment]
I contacted `4stats.io` admins and they replied with a detailed explanation. I described their approach in this document:
https://github.com/catamphetamine/chanchan/blob/master/docs/4chan.org/API.md#get-popular-threads-list

**Comment by desuwa** [comment]
There's no endpoint for that. You'll have to calculate the score yourself. Something like what you posted above or just calculate some kind of  "recent activity" score for each thread based on the amount of new replies in the past X minutes.
