### ISSUE TITLE
7-day autosage on /vr/

### ISSUE THREAD

**Issue by ccd0** [4chan/4chan-API#65]
Is this going to be documented anywhere?

Shameful that 4chan has yet again responded to ghost-bumping by harming ordinary users rather than [fixing the core problem](https://github.com/fallenPineapple/NPFchan/commit/3cb3ef692e315df54d24f2c4a240e4fa5513297e).

**Comment by desuwa** [comment]
> Is this going to be documented anywhere?

Probably not. It's more of an internal setting which doesn't need to be exposed in boards.json

We'll fix the bumplimit prop in thread jsons not being set properly though.
