### ISSUE TITLE
Request: threads.json post count

### ISSUE THREAD

**Issue by halcyons** [4chan/4chan-API#68]
Is it possible to get an indicator in` threads.json` that either shows the number of posts in each thread, or alter the behavior of `last_modified` to exclude post deletions? 
Archivers and other tools could opt to make less requests if they could decide when to fetch a thread based on changes to post counts.

**Comment by desuwa** [comment]
`threads.json` shows the reply count now

**Comment by halcyons** [comment]
Thank you!
