### ISSUE TITLE
Image Download

### ISSUE THREAD

**Issue by realTobby** [4chan/4chan-API#74]
Hello, does 4chan not allow Image Download? I keep getting 403 Error when trying to download an Image. I get the Image URL from a specified Thread and a specified Post if it has an image attached to it. I can show the picture inside a control. But as soon as I try to download it iget the error. 

I just want to know if 4chan in general allow Image Download or not.
Thanks, Tobby

**Comment by desuwa** [comment]
What's the URL you are trying to access?

It's probably related to the hotlink protection (wrong referrer header). Look at the response body you get in your 403 error.

**Comment by realTobby** [comment]
hmm seemed to be my fault. Somwhow I used the wrong subdomain? I use is2.4chan now and download works now. I used 4cdn or something like that before. This can be closed now. But thanks!
