### ISSUE TITLE
A full list of capcodes

### ISSUE THREAD

**Issue by catamphetamine** [4chan/4chan-API#76]
The docs have been rewritten recently and it's much clearer now.
`capcode`s even are kinda documented now.
For example, here:
https://github.com/4chan/4chan-API/blob/master/pages/Catalog.md

* mod
* admin
* admin_highlight
* manager
* developer
* founder

For simplicity, I [assume](https://github.com/catamphetamine/imageboard/blob/master/source/chan/4chan/index.json) everyone's "administrator" except "mod" and "manager" which are moderators.

Today I noticed there's another undocumented `capcode`: `"verified"` ("Anamanaguchi ## Verified").
It happened on the [`/vip/`](http://boards.4channel.org/vip/thread/94446) board.
I'm not a `4chan.org` user so I don't know what "Verified" status means exactly.
`/vip/` board seems to only accept posts from 4chan Pass users, but "Verified" seems to be even different.
Would you explain?
I suppose it's just a "swag" status, and don't assume any privileges other that showing off.

**Comment by desuwa** [comment]
It's really just a "verified" status. It's used for things like AMAs and such.

**Comment by catamphetamine** [comment]
Oh, I see.
So it's like "Gabe Newell (verified)".
Ok.
