### ISSUE TITLE
Request: Public ban flag

### ISSUE THREAD

**Issue by cyggy** [4chan/4chan-API#77]
Since it's the only instance of post text changing after creation, would it be possible to have an API attribute for public banned posts? `pubban: 1` when a post is publicly banned etc.

This would be very convenient for updating cached post data without having to make additional requests to the server, or additional text diff tracking or parsing for certain kinds of applications. File deletions are already tracked in the API for similar "content has changed" reasons.

Alternatively, adding a `pubban: 1` attribute to OP JSON objects if there's a public ban present in the thread would be nice too.

**Comment by desuwa** [comment]
We can't really do that as we don't store that information separately. The public ban text is just appended to the post and that's it.

**Comment by cyggy** [comment]
Alrighth
