### ISSUE TITLE
Archives falsely update Last-Modified timestamp

### ISSUE THREAD

**Issue by shiimizu** [4chan/4chan-API#78]
`archive.json` emits an updated `Last-Modified` whenever `threads.json` is updated even though the archive contents are **unmodified**.

This generates unnecessary bandwidth for those relying on `Last-Modified` from `If-Modified-Since` which the API rules states to use.

**Comment by desuwa** [comment]
> archive.json emits an updated Last-Modified whenever threads.json is updated

This should be fixed now.

Although there will still be some rare cases where archive.json is regenerated even though the archives didn't change.

**Comment by shiimizu** [comment]
Thanks for the quick response. Yeah it seems to be working fine now.
